name: 'Continuous Integration'

on: 
  # Execute testing on push to development, main, and release branches
  push:
    branches: ["main", "develop", "release/*", "feature/*"]
  # Execute when pulling to main
  pull_request:
    branches: ["main"]

jobs:
  # Test model and api
  test:
    runs-on: ubuntu-latest
    steps:
      # Use ptyhon 3.12
      - uses: actions/checkout@v4
      - name: Python set up
        uses: actions/checkout@v4
        with: 
          python-version: '3.12'
      # Install requirements for running and testing
      - name: install dependencies
        run: | 
          pip install -r requirements-test.txt 
          pip install -r requirements.txt
      # Test model
      - name: test model
        run: make model-test
      # Test api
      - name: test api
        run: make api-test
  # Build test
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Docker build test
        run: docker build -t mle-diegohiriart .
      